#users (one user has taken 2 surveys.)
User.create(email: "test1@example.com", username: "user1", password: "password")
User.create(email: "demo2@example.com", username: "user2", password: "password")
User.create(email: "derp3@example.com", username: "user3", password: "password")
User.create(email: "herp4@example.com", username: "user4", password: "password")
#surveys
Survey.create(title: "Marvel Comic Books", user_id: 1)
Survey.create(title: "StarWars Characters", user_id: 2)
Survey.create(title: "Favorite Invertibrates", user_id: 3)
Survey.create(title: "Favorite Pets", user_id: 4)
#questions
Question.create(question_text: "State your favorite Marvel hero.", survey_id: 1)
Question.create(question_text: "Which StarWars character do you relate to most?", survey_id: 2)
Question.create(question_text: "State your favorite spineless creature", survey_id: 3)
Question.create(question_text: "Dogs or Cats?", survey_id: 4)
#the users and the surveys they took
Participation.create(user_id: 1, survey_id: 1)
Participation.create(user_id: 2, survey_id: 2)
Participation.create(user_id: 3, survey_id: 3)
Participation.create(user_id: 4, survey_id: 4)
Participation.create(user_id: 1, survey_id: 2)
#all choices for all questions
Choice.create(choice_text: "Spiderman", question_id: 1)
Choice.create(choice_text: "Ironman", question_id: 1)
Choice.create(choice_text: "Obi-Wan Kenobi", question_id: 2)
Choice.create(choice_text: "Han Solo", question_id: 2)
Choice.create(choice_text: "Troglobites", question_id: 3)
Choice.create(choice_text: "Jelly Fish", question_id: 3)
Choice.create(choice_text: "dog", question_id: 4)
Choice.create(choice_text: "cat", question_id: 4)
#user responses
SurveyResponse.create(participations_id: 1, choices_id: 2)
SurveyResponse.create(participations_id: 2, choices_id: 4)
SurveyResponse.create(participations_id: 3, choices_id: 6)
SurveyResponse.create(participations_id: 4, choices_id: 7)
SurveyResponse.create(participations_id: 5, choices_id: 3)
